import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin} from 'react-icons/ai';
import Image from 'next/image';
import Malanpic from '../public/Malanpic.jpeg';
import {useState} from 'react';
import React from 'react';
import getintouch from './getintouch';

import About from './About';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Malan Bruwer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-butons dark:text-white'>MALAN</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill 
                  onClick={() => setDarkMode(!darkMode)}
                  className='cursor-pointer text-2xl dark:text-white'/>
              </li>
              <li>
                <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                  download href="Malan-Bruwer-Dev.pdf">
                    Resume
                  </a>
              </li>
              <li>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                  href="getintouch">
                    Contact
                  </a>

              </li>

            </ul>
          </nav>
          <About />
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/malan-bruwer-b3b059113/">
            <AiFillLinkedin />
            </a>
          </div>
          <div className='relative mx-auto rounded-full w-80 h-80 mt-20 overflow-hidden'>
            {<Image src={Malanpic} layout='fill' objectFit='cover'/>}
          </div>
        </section>

        <section>
          <div className='text-center'>
              <h3 className='text-3xl py-1 dark:text-white'>
                Services
              </h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'> My freelance clients include multiple businesses such as retail, requiring <span className='text-teal-500'>brand design and site layout</span> and hospitality, requiring <span className='text-teal-500'>web development</span>. </p>
          </div>
        </section>
      </main>
    </div>
      
  );
}

